services:
  minecraft-server:
    image: eclipse-temurin:21-jre-jammy
    container_name: minecraft
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - ./scripts:/opt/minecraft/scripts:rw
      - ./data:/data:rw
    command: sh /opt/minecraft/scripts/build-and-run.sh

networks:
  default:
    external: true
    name: proxy
